# Generated by Django 3.2.13 on 2022-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=10, verbose_name='獎項名稱')),
                ('lnum', models.IntegerField(verbose_name='獎項數量')),
            ],
            options={
                'verbose_name': '獎項名稱',
                'verbose_name_plural': '獎項名稱',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, verbose_name='員工編號')),
                ('uname', models.CharField(max_length=10, verbose_name='員工姓名')),
                ('lottery_state', models.IntegerField(verbose_name='中獎')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
            },
        ),
    ]
