# Generated by Django 3.2.13 on 2022-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lottery_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, verbose_name='員工編號')),
                ('urand', models.IntegerField(verbose_name='中獎亂數')),
            ],
        ),
    ]
