# Generated by Django 3.2.13 on 2022-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, verbose_name='uid')),
                ('uname', models.CharField(max_length=30, verbose_name='uid')),
                ('group', models.IntegerField(verbose_name='group')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to='UploadedFiles/'),
        ),
    ]
