# Generated by Django 3.2.13 on 2022-05-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20220505_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lottery_prize',
            new_name='prize',
        ),
    ]
