# Generated by Django 3.2.13 on 2022-05-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_rename_lottery_prize_prize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prize',
        ),
    ]
